"""Scaffold rehearse.yaml from a target URL."""

from __future__ import annotations

import re
from pathlib import Path
from urllib.parse import urlparse

import yaml


def _slug_from_url(url: str) -> str:
    host = urlparse(url).netloc or "app"
    slug = re.sub(r"[^a-z0-9]+", "-", host.lower()).strip("-")
    return slug or "app"


def _product_name(url: str, name: str | None) -> str:
    if name:
        return name
    host = urlparse(url).netloc or url
    return host.replace("www.", "").split(".")[0].title()


def build_config(
    target_url: str,
    *,
    product_name: str | None = None,
    run_id_prefix: str | None = None,
    with_auth: bool = False,
    crawl_enabled: bool = True,
) -> dict:
    base = target_url.rstrip("/")
    prefix = run_id_prefix or _slug_from_url(base)
    product = _product_name(base, product_name)

    cfg: dict = {
        "run": {
            "target_url": base,
            "run_id_prefix": prefix,
            "product_name": product,
        },
        "crawl": {
            "enabled": crawl_enabled,
            "max_depth": 2,
            "max_pages": 30,
            "supplement_journeys": True,
        },
        "personas": [
            {
                "id": "p1-evaluator",
                "name": "First-time evaluator",
                "role": "prospect / new user",
                "goals": ["Understand value from landing and primary workflow"],
            },
            {
                "id": "p2-operator",
                "name": "Daily operator",
                "role": "power user",
                "goals": ["Complete core tasks quickly and reliably"],
            },
            {
                "id": "p3-admin",
                "name": "Admin / buyer",
                "role": "IT admin",
                "goals": ["Verify access boundaries and trust signals"],
            },
        ],
        "journeys": [
            {
                "id": "j1-land",
                "name": "Land on primary surface",
                "steps": [{"action": "navigate", "url": f"{base}/"}, {"action": "wait", "value": "2000"}],
            },
            {
                "id": "j2-core",
                "name": "Core workflow",
                "steps": [{"action": "navigate", "url": f"{base}/"}, {"action": "wait", "value": "2000"}],
            },
            {
                "id": "j3-depth",
                "name": "Secondary module",
                "steps": [{"action": "navigate", "url": f"{base}/"}, {"action": "wait", "value": "1500"}],
            },
            {
                "id": "j4-search",
                "name": "Search or discovery",
                "steps": [{"action": "navigate", "url": f"{base}/"}, {"action": "wait", "value": "1500"}],
            },
            {
                "id": "j5-admin",
                "name": "Admin or settings boundary",
                "steps": [{"action": "navigate", "url": f"{base}/admin"}, {"action": "wait", "value": "1500"}],
            },
        ],
        "budgets": {
            "max_steps_per_journey": 12,
            "max_run_seconds": 1200,
            "step_timeout_ms": 45000,
        },
    }

    if with_auth:
        cfg["auth"] = {
            "login_path": "/login",
            "email_env": "REHEARSE_EMAIL",
            "password_env": "REHEARSE_PASSWORD",
            "email_label": "Email",
            "password_label": "Password",
            "submit_label": "Login",
        }
        cfg["journeys"][0]["steps"] = [
            {"action": "navigate", "url": f"{base}/database"},
            {"action": "wait", "value": "2000"},
        ]

    return cfg


def write_config(path: Path, config: dict) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Generated by: rehearse init\n"
        "# Edit journeys to match your product — see examples/enterprise-authenticated.yaml\n\n"
    )
    path.write_text(header + yaml.dump(config, default_flow_style=False, sort_keys=False))
    return path
