/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RunnerRouteImport } from './routes/runner'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InitRouteImport } from './routes/init'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CliRouteImport } from './routes/cli'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as WorkspaceSlugRouteImport } from './routes/$workspaceSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as ExperimentJobIdRouteImport } from './routes/experiment.$jobId'
import { Route as CohortJobIdRouteImport } from './routes/cohort.$jobId'
import { Route as WorkspaceSlugTrendsRouteImport } from './routes/$workspaceSlug.trends'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/$workspaceSlug.settings'
import { Route as WorkspaceSlugRunsRouteImport } from './routes/$workspaceSlug.runs'
import { Route as WorkspaceSlugRunnerRouteImport } from './routes/$workspaceSlug.runner'
import { Route as WorkspaceSlugPersonasRouteImport } from './routes/$workspaceSlug.personas'
import { Route as WorkspaceSlugDashboardRouteImport } from './routes/$workspaceSlug.dashboard'
import { Route as WorkspaceSlugConfigRouteImport } from './routes/$workspaceSlug.config'
import { Route as WorkspaceSlugCompareRouteImport } from './routes/$workspaceSlug.compare'
import { Route as WorkspaceSlugRunsIndexRouteImport } from './routes/$workspaceSlug.runs.index'
import { Route as WorkspaceSlugRunsRunIdRouteImport } from './routes/$workspaceSlug.runs.$runId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerRoute = RunnerRouteImport.update({
  id: '/runner',
  path: '/runner',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentJobIdRoute = ExperimentJobIdRouteImport.update({
  id: '/experiment/$jobId',
  path: '/experiment/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortJobIdRoute = CohortJobIdRouteImport.update({
  id: '/cohort/$jobId',
  path: '/cohort/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugTrendsRoute = WorkspaceSlugTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugRunsRoute = WorkspaceSlugRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugRunnerRoute = WorkspaceSlugRunnerRouteImport.update({
  id: '/runner',
  path: '/runner',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugPersonasRoute = WorkspaceSlugPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugDashboardRoute = WorkspaceSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugConfigRoute = WorkspaceSlugConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugCompareRoute = WorkspaceSlugCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugRunsIndexRoute = WorkspaceSlugRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRunsRoute,
} as any)
const WorkspaceSlugRunsRunIdRoute = WorkspaceSlugRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => WorkspaceSlugRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/workflows': typeof WorkflowsRoute
  '/$workspaceSlug/compare': typeof WorkspaceSlugCompareRoute
  '/$workspaceSlug/config': typeof WorkspaceSlugConfigRoute
  '/$workspaceSlug/dashboard': typeof WorkspaceSlugDashboardRoute
  '/$workspaceSlug/personas': typeof WorkspaceSlugPersonasRoute
  '/$workspaceSlug/runner': typeof WorkspaceSlugRunnerRoute
  '/$workspaceSlug/runs': typeof WorkspaceSlugRunsRouteWithChildren
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug/trends': typeof WorkspaceSlugTrendsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
  '/$workspaceSlug/runs/$runId': typeof WorkspaceSlugRunsRunIdRoute
  '/$workspaceSlug/runs/': typeof WorkspaceSlugRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/workflows': typeof WorkflowsRoute
  '/$workspaceSlug/compare': typeof WorkspaceSlugCompareRoute
  '/$workspaceSlug/config': typeof WorkspaceSlugConfigRoute
  '/$workspaceSlug/dashboard': typeof WorkspaceSlugDashboardRoute
  '/$workspaceSlug/personas': typeof WorkspaceSlugPersonasRoute
  '/$workspaceSlug/runner': typeof WorkspaceSlugRunnerRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug/trends': typeof WorkspaceSlugTrendsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs': typeof RunsIndexRoute
  '/$workspaceSlug/runs/$runId': typeof WorkspaceSlugRunsRunIdRoute
  '/$workspaceSlug/runs': typeof WorkspaceSlugRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap': typeof SitemapRoute
  '/workflows': typeof WorkflowsRoute
  '/$workspaceSlug/compare': typeof WorkspaceSlugCompareRoute
  '/$workspaceSlug/config': typeof WorkspaceSlugConfigRoute
  '/$workspaceSlug/dashboard': typeof WorkspaceSlugDashboardRoute
  '/$workspaceSlug/personas': typeof WorkspaceSlugPersonasRoute
  '/$workspaceSlug/runner': typeof WorkspaceSlugRunnerRoute
  '/$workspaceSlug/runs': typeof WorkspaceSlugRunsRouteWithChildren
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/$workspaceSlug/trends': typeof WorkspaceSlugTrendsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/join/$token': typeof JoinTokenRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
  '/$workspaceSlug/runs/$runId': typeof WorkspaceSlugRunsRunIdRoute
  '/$workspaceSlug/runs/': typeof WorkspaceSlugRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceSlug'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/runner'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/workflows'
    | '/$workspaceSlug/compare'
    | '/$workspaceSlug/config'
    | '/$workspaceSlug/dashboard'
    | '/$workspaceSlug/personas'
    | '/$workspaceSlug/runner'
    | '/$workspaceSlug/runs'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/trends'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/join/$token'
    | '/runs/$runId'
    | '/runs/'
    | '/$workspaceSlug/runs/$runId'
    | '/$workspaceSlug/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceSlug'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/runner'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/workflows'
    | '/$workspaceSlug/compare'
    | '/$workspaceSlug/config'
    | '/$workspaceSlug/dashboard'
    | '/$workspaceSlug/personas'
    | '/$workspaceSlug/runner'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/trends'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/join/$token'
    | '/runs/$runId'
    | '/runs'
    | '/$workspaceSlug/runs/$runId'
    | '/$workspaceSlug/runs'
  id:
    | '__root__'
    | '/'
    | '/$workspaceSlug'
    | '/admin'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/onboarding'
    | '/recommendations'
    | '/runner'
    | '/signin'
    | '/signup'
    | '/sitemap'
    | '/workflows'
    | '/$workspaceSlug/compare'
    | '/$workspaceSlug/config'
    | '/$workspaceSlug/dashboard'
    | '/$workspaceSlug/personas'
    | '/$workspaceSlug/runner'
    | '/$workspaceSlug/runs'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/trends'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/join/$token'
    | '/runs/$runId'
    | '/runs/'
    | '/$workspaceSlug/runs/$runId'
    | '/$workspaceSlug/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  CliRoute: typeof CliRoute
  CompareRoute: typeof CompareRoute
  ConfigRoute: typeof ConfigRoute
  InitRoute: typeof InitRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RunnerRoute: typeof RunnerRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapRoute: typeof SitemapRoute
  WorkflowsRoute: typeof WorkflowsRoute
  CohortJobIdRoute: typeof CohortJobIdRoute
  ExperimentJobIdRoute: typeof ExperimentJobIdRoute
  JoinTokenRoute: typeof JoinTokenRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner': {
      id: '/runner'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof RunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug': {
      id: '/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment/$jobId': {
      id: '/experiment/$jobId'
      path: '/experiment/$jobId'
      fullPath: '/experiment/$jobId'
      preLoaderRoute: typeof ExperimentJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort/$jobId': {
      id: '/cohort/$jobId'
      path: '/cohort/$jobId'
      fullPath: '/cohort/$jobId'
      preLoaderRoute: typeof CohortJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/trends': {
      id: '/$workspaceSlug/trends'
      path: '/trends'
      fullPath: '/$workspaceSlug/trends'
      preLoaderRoute: typeof WorkspaceSlugTrendsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/settings': {
      id: '/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/runs': {
      id: '/$workspaceSlug/runs'
      path: '/runs'
      fullPath: '/$workspaceSlug/runs'
      preLoaderRoute: typeof WorkspaceSlugRunsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/runner': {
      id: '/$workspaceSlug/runner'
      path: '/runner'
      fullPath: '/$workspaceSlug/runner'
      preLoaderRoute: typeof WorkspaceSlugRunnerRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/personas': {
      id: '/$workspaceSlug/personas'
      path: '/personas'
      fullPath: '/$workspaceSlug/personas'
      preLoaderRoute: typeof WorkspaceSlugPersonasRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/dashboard': {
      id: '/$workspaceSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$workspaceSlug/dashboard'
      preLoaderRoute: typeof WorkspaceSlugDashboardRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/config': {
      id: '/$workspaceSlug/config'
      path: '/config'
      fullPath: '/$workspaceSlug/config'
      preLoaderRoute: typeof WorkspaceSlugConfigRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/compare': {
      id: '/$workspaceSlug/compare'
      path: '/compare'
      fullPath: '/$workspaceSlug/compare'
      preLoaderRoute: typeof WorkspaceSlugCompareRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/runs/': {
      id: '/$workspaceSlug/runs/'
      path: '/'
      fullPath: '/$workspaceSlug/runs/'
      preLoaderRoute: typeof WorkspaceSlugRunsIndexRouteImport
      parentRoute: typeof WorkspaceSlugRunsRoute
    }
    '/$workspaceSlug/runs/$runId': {
      id: '/$workspaceSlug/runs/$runId'
      path: '/$runId'
      fullPath: '/$workspaceSlug/runs/$runId'
      preLoaderRoute: typeof WorkspaceSlugRunsRunIdRouteImport
      parentRoute: typeof WorkspaceSlugRunsRoute
    }
  }
}

interface WorkspaceSlugRunsRouteChildren {
  WorkspaceSlugRunsRunIdRoute: typeof WorkspaceSlugRunsRunIdRoute
  WorkspaceSlugRunsIndexRoute: typeof WorkspaceSlugRunsIndexRoute
}

const WorkspaceSlugRunsRouteChildren: WorkspaceSlugRunsRouteChildren = {
  WorkspaceSlugRunsRunIdRoute: WorkspaceSlugRunsRunIdRoute,
  WorkspaceSlugRunsIndexRoute: WorkspaceSlugRunsIndexRoute,
}

const WorkspaceSlugRunsRouteWithChildren =
  WorkspaceSlugRunsRoute._addFileChildren(WorkspaceSlugRunsRouteChildren)

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugCompareRoute: typeof WorkspaceSlugCompareRoute
  WorkspaceSlugConfigRoute: typeof WorkspaceSlugConfigRoute
  WorkspaceSlugDashboardRoute: typeof WorkspaceSlugDashboardRoute
  WorkspaceSlugPersonasRoute: typeof WorkspaceSlugPersonasRoute
  WorkspaceSlugRunnerRoute: typeof WorkspaceSlugRunnerRoute
  WorkspaceSlugRunsRoute: typeof WorkspaceSlugRunsRouteWithChildren
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugTrendsRoute: typeof WorkspaceSlugTrendsRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugCompareRoute: WorkspaceSlugCompareRoute,
  WorkspaceSlugConfigRoute: WorkspaceSlugConfigRoute,
  WorkspaceSlugDashboardRoute: WorkspaceSlugDashboardRoute,
  WorkspaceSlugPersonasRoute: WorkspaceSlugPersonasRoute,
  WorkspaceSlugRunnerRoute: WorkspaceSlugRunnerRoute,
  WorkspaceSlugRunsRoute: WorkspaceSlugRunsRouteWithChildren,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugTrendsRoute: WorkspaceSlugTrendsRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  CliRoute: CliRoute,
  CompareRoute: CompareRoute,
  ConfigRoute: ConfigRoute,
  InitRoute: InitRoute,
  IntegrationsRoute: IntegrationsRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  RecommendationsRoute: RecommendationsRoute,
  RunnerRoute: RunnerRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapRoute: SitemapRoute,
  WorkflowsRoute: WorkflowsRoute,
  CohortJobIdRoute: CohortJobIdRoute,
  ExperimentJobIdRoute: ExperimentJobIdRoute,
  JoinTokenRoute: JoinTokenRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
