/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as RunnerRouteImport } from './routes/runner'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InitRouteImport } from './routes/init'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CliRouteImport } from './routes/cli'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as ExperimentJobIdRouteImport } from './routes/experiment.$jobId'
import { Route as CohortJobIdRouteImport } from './routes/cohort.$jobId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerRoute = RunnerRouteImport.update({
  id: '/runner',
  path: '/runner',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentJobIdRoute = ExperimentJobIdRouteImport.update({
  id: '/experiment/$jobId',
  path: '/experiment/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortJobIdRoute = CohortJobIdRouteImport.update({
  id: '/cohort/$jobId',
  path: '/cohort/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/sitemap': typeof SitemapRoute
  '/trends': typeof TrendsRoute
  '/workflows': typeof WorkflowsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/sitemap': typeof SitemapRoute
  '/trends': typeof TrendsRoute
  '/workflows': typeof WorkflowsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/cli': typeof CliRoute
  '/compare': typeof CompareRoute
  '/config': typeof ConfigRoute
  '/init': typeof InitRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/recommendations': typeof RecommendationsRoute
  '/runner': typeof RunnerRoute
  '/sitemap': typeof SitemapRoute
  '/trends': typeof TrendsRoute
  '/workflows': typeof WorkflowsRoute
  '/cohort/$jobId': typeof CohortJobIdRoute
  '/experiment/$jobId': typeof ExperimentJobIdRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/recommendations'
    | '/runner'
    | '/sitemap'
    | '/trends'
    | '/workflows'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/recommendations'
    | '/runner'
    | '/sitemap'
    | '/trends'
    | '/workflows'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/runs/$runId'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/cli'
    | '/compare'
    | '/config'
    | '/init'
    | '/integrations'
    | '/library'
    | '/recommendations'
    | '/runner'
    | '/sitemap'
    | '/trends'
    | '/workflows'
    | '/cohort/$jobId'
    | '/experiment/$jobId'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  CliRoute: typeof CliRoute
  CompareRoute: typeof CompareRoute
  ConfigRoute: typeof ConfigRoute
  InitRoute: typeof InitRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LibraryRoute: typeof LibraryRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RunnerRoute: typeof RunnerRoute
  SitemapRoute: typeof SitemapRoute
  TrendsRoute: typeof TrendsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  CohortJobIdRoute: typeof CohortJobIdRoute
  ExperimentJobIdRoute: typeof ExperimentJobIdRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runner': {
      id: '/runner'
      path: '/runner'
      fullPath: '/runner'
      preLoaderRoute: typeof RunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment/$jobId': {
      id: '/experiment/$jobId'
      path: '/experiment/$jobId'
      fullPath: '/experiment/$jobId'
      preLoaderRoute: typeof ExperimentJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort/$jobId': {
      id: '/cohort/$jobId'
      path: '/cohort/$jobId'
      fullPath: '/cohort/$jobId'
      preLoaderRoute: typeof CohortJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  CliRoute: CliRoute,
  CompareRoute: CompareRoute,
  ConfigRoute: ConfigRoute,
  InitRoute: InitRoute,
  IntegrationsRoute: IntegrationsRoute,
  LibraryRoute: LibraryRoute,
  RecommendationsRoute: RecommendationsRoute,
  RunnerRoute: RunnerRoute,
  SitemapRoute: SitemapRoute,
  TrendsRoute: TrendsRoute,
  WorkflowsRoute: WorkflowsRoute,
  CohortJobIdRoute: CohortJobIdRoute,
  ExperimentJobIdRoute: ExperimentJobIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
